### ISSUE TITLE
Shutdown command windows PC from NAS

### ISSUE THREAD

**Issue by Tontonpat** [AlexGustafsson/homebridge-wol#103]
Hello, thank you for this plugin.
It show me if my PC is on or off, but i can't shutdown or wake it up.
Homebridge is installed on my NAS Synology.
Can you explain the right command to shutdown please?

net rpc shutdown --ipaddress 192.168.1.74 --user ****%**** doesn't work

**Comment by AlexGustafsson** [comment]
What error do you get when you run the command?

**Comment by Tontonpat** [comment]
Sorry for the delay, here the error:
And sorry for my english, i'm french ;-)

NetworkDevice "HPZ440" went from status "Online" to "Shutting Down"
Attempting to shut down "HPZ440" (192.168.1.**) using "net"
An error occured while trying to shut down "HPZ440" (192.168.1.**): Error: Command failed: net rpc shutdown --ipaddress 192.168.1.** --user $$$$$$%$$$$$$
Can't load /etc/samba/smb.conf - run testparm to debug it

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'net rpc shutdown --ipaddress 192.168.1.** --user $$$$$$%$$$$$$$',
  stdout: '',
  stderr: "Can't load /etc/samba/smb.conf - run testparm to debug it\n"
}
Waiting for shutdown grace time (15000ms) for "HPZ440" (192.168.1.**)

**Comment by AlexGustafsson** [comment]
No worries!

First of, did you censor the IP address or did you write “192.168.1.” in the config file? If you didn’t change the logs, make sure that the IP is an actual IP address such as 192.168.1.1.

Now, the actual error seems to have to do with the command you’re executing:

```
Can't load /etc/samba/smb.conf - run testparm to debug it
```

This tells us that the shutdown command itself fails. You can debug this further by trying to run the command outside of Homebridge WoL. Unfortunately I’m not accustomed to using samba on Linux, so I cannot help you further.

To try to debug this on your own, first try to track down what the root cause of the error is. There seems to be some missing configuration file for the samba package, causing the command to fail. Try to run `testparm` as the error you’re receiving tells us.

**Comment by AlexGustafsson** [comment]
Closing due to inactivity. Feel free to reopen if it’s not resolved.
