### ISSUE TITLE
Cannot read propert 'split' of null

### ISSUE THREAD

**Issue by yceballost** [AlexGustafsson/homebridge-wol#107]
### Backstory
I'm trying to turn on my Mac with wol

### Issue
I can't turn on the pc

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of null
    at NetworkDevice.wake (/usr/lib/node_modules/homebridge-wol/lib/network-device.js:177:51)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at NetworkDevice.setOnline (/usr/lib/node_modules/homebridge-wol/lib/network-device.js:130:9)
(node:25039) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25039) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Environment
* os & os version: Raspbian GNU/Linux Buster (10)
* node version: v12.18.2
* homebridge version: 1.1.1
* homebridge-wol version: 4.2.1

### Configuration
My configuration looks like this:
```
{
            "name": "Hackintosh",
            "ip": "192.168.1.35",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "mac": "<mac-address>",
            "broadcastAddress": "192.168.1.255",
            "startCommand": "ssh yayo@192.168.1.35 caffeinate -u -t 300",
            "wakeGraceTime": 45,
            "shutdownCommand": "ssh yayo@192.168.1.35 sudo shutdown -h now",
            "shutdownGraceTime": 15,
            "log": true,
            "logPinger": false,
            "debugLog": false,
            "returnEarly": false,
            "accessory": "NetworkDevice"
        }
```

**Comment by AlexGustafsson** [comment]
Try `wakeCommand` instead of `startCommand`. See the README for full documentation.

**Comment by yceballost** [comment]
damn! works! I thought that wakeCommand was for unsleep the machine.

Thanks!
