### ISSUE TITLE
Unique Seriel Numbers

### ISSUE THREAD

**Issue by Salvora** [AlexGustafsson/homebridge-wol#117]
### Backstory
I have a working setup with wol and I wanted to integrate this setup to home-assistant. The integration went fine, however, only single instance of a device showed up out of 6.
So, after a little bit research, I did find a similar issue and contacted the very friendly and helpful HA devs.

https://github.com/home-assistant/core/issues/24797

### Issue
It turns out that for HA to function, every device needs to have a unique serial number for it is the standard of homekit.
Can we get a serial number field that uniquely identifies the devices?

**Comment by AlexGustafsson** [comment]
Thanks for reaching out! I’ll try to fix it as soon as possible.

**Comment by AlexGustafsson** [comment]
Should be fixed in master now. I haven't been able to test it since `homebridge-config-ui-x` seems to have some issue with `commander`:

```
[2020-09-05 16:33:00] Loaded config.json with 6 accessories and 1 platforms.
[2020-09-05 16:33:00] ---
[2020-09-05 16:33:00] Loaded plugin: homebridge-wol@4.3.0
[2020-09-05 16:33:00] Registering accessory 'homebridge-wol.NetworkDevice'
[2020-09-05 16:33:00] ---
[2020-09-05 16:33:00] Loaded plugin: homebridge-config-ui-x@4.27.1
[2020-09-05 16:33:00] Registering platform 'homebridge-config-ui-x.config'
[2020-09-05 16:33:00] ---
[2020-09-05 16:33:00] Loading 1 platforms...
[2020-09-05 16:33:00] [Config] Initializing config platform...
[2020-09-05 16:33:00] Error: option 'plugin-path' clashes with existing property 'pluginPath' on Command
- call storeOptionsAsProperties(false) to store option values safely,
- or call storeOptionsAsProperties(true) to suppress this check,
- or change option name

Read more on https://git.io/JJc0W
    at Command._checkForOptionNameClash (/path/to/homebridge-wol/node_modules/commander/index.js:472:13)
    at Command._optionEx (/path/to/homebridge-wol/node_modules/commander/index.js:499:10)
    at Command.option (/path/to/homebridge-wol/node_modules/commander/index.js:622:17)
    at new HomebridgeConfigUi (/path/to/homebridge-wol/node_modules/homebridge-config-ui-x/src/index.ts:29:8)
    at /path/to/homebridge-wol/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/path/to/homebridge-wol/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/path/to/homebridge-wol/node_modules/homebridge/src/server.ts:153:29)
    at cli (/path/to/homebridge-wol/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/path/to/homebridge-wol/node_modules/homebridge/bin/homebridge:17:22)
```

The version of homebridge nor homebridge-config-ui-x has changed since the last time I ran the tests successfully, so I'm not sure what's up with that.

I'll postpone a release until I can test the fix, but you should be able to install from master using git and `npm link`.

**Comment by Salvora** [comment]
wow, thanks for the quick update.
I will check that but probably I will wait for the release because I don't have a test environment right now.

**Comment by Salvora** [comment]
Installed from master branch. I had to install globally otherwise it was throwing errors. It is working. Thanks.
