### ISSUE TITLE
Error loading plugin on RPi

### ISSUE THREAD

**Issue by JoniSykes** [AlexGustafsson/homebridge-wol#12]
```
[1/7/2017, 5:46:09 PM] ERROR LOADING PLUGIN homebridge-wol:
[1/7/2017, 5:46:09 PM] Error: Cannot find module './build/Release/raw'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wol/node_modules/raw-socket/index.js:4:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by JoniSykes** [comment]
Never mind, issue was with the plugin being install for pi user not root user.
