### ISSUE TITLE
NT_STATUS_LOGON_FAILURE

### ISSUE THREAD

**Issue by costispavlou** [AlexGustafsson/homebridge-wol#130]
Hi Alex, first of all thank you for this wonderful plugin. 
I have an issue that started a couple of days ago and I have no idea what's wrong. 
I'm having these errors which resulted me in having to remove the plugin and reinstall, however the same issues apply. 

> 11/10/2020, 7:01:53 PM [PC] Attempting to shut down "PC" (192.168.0.66) using "net"
> 11/10/2020, 7:01:53 PM [PC] An error occured while trying to shut down "PC" (192.168.0.66): Error: Command failed: net rpc shutdown --ipaddress 192.168.0.66 --user ********%********** <- hidden for safety 
> mkdir failed on directory /var/run/samba/msg.lock: Permission denied
> Could not connect to server 192.168.0.66
> The username or password was not correct. **<--- the password is correct.** 
> Connection failed: NT_STATUS_LOGON_FAILURE
> Could not connect to server 192.168.0.66
> The username or password was not correct.
> Connection failed: NT_STATUS_LOGON_FAILURE
> 
>     at ChildProcess.exithandler (child_process.js:295:12)
>     at ChildProcess.emit (events.js:210:5)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
>   killed: false,
>   code: 255,
>   signal: null,
>   cmd: 'net rpc shutdown --ipaddress 192.168.0.66 --user xxxx%xxxx',
>   stdout: '',
>   stderr: 'mkdir failed on directory /var/run/samba/msg.lock: Permission denied\n' +
>     'Could not connect to server 192.168.0.66\n' +
>     'The username or password was not correct.\n' +

here's my config page as well.

![image](https://user-images.githubusercontent.com/57916603/98707085-4da33c80-2388-11eb-9105-4f3b011047da.png)

please please help me ? thank you so much in advance.

**Comment by AlexGustafsson** [comment]
You mentioned it started a couple of days ago. Did you do anything of the following recently?

1. Upgrade homebridge-ui-x
2. Upgrade homebridge-wol
3. Change your configuration

It is weird if it just appeared out of the blue, but entirely possible.

**Comment by costispavlou** [comment]
honestly I don't know.. I even removed the app and retried it. I have absolutely no clue. 
What's my password have to do with anything though? IP is correct, username is correct, password is correct (i changed it on my microsoft account and same error)

**Comment by AlexGustafsson** [comment]
If you haven't already - try to use your Microsoft account (email and password) as the credentials instead of any local account.

Also, if you want more security you should really think about using SSH and SSH keys instead. There's a guide including the setup here: https://github.com/AlexGustafsson/homebridge-wol/wiki/Running-on-Synology-Docker-and-turn-Windows-10-on-off-using-SSH-and-Samba.

**Comment by costispavlou** [comment]
I've fixed it. Apparently something effed the settings of the pci lan controller. enabled magic packets again and fixed the boot sequence. 
the shutdown sequence issue however remains the same

**Comment by AlexGustafsson** [comment]
Have you been able to try the SSH solution?

**Comment by AlexGustafsson** [comment]
Closing due to inactivity. Feel free to head into the discussions (https://github.com/AlexGustafsson/homebridge-wol/discussions) if you have any further questions.
