### ISSUE TITLE
Homebridge crashing of error loading plugin

### ISSUE THREAD

**Issue by Seestali** [AlexGustafsson/homebridge-wol#23]
Everytime I start homebridge (with sudo) this appears:

`[2017-8-20 10:41:51] ====================
[2017-8-20 10:41:51] ERROR LOADING PLUGIN homebridge-wol:
[2017-8-20 10:41:51] Error: Cannot find module './build/Release/raw'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-wol/node_modules/raw-socket/index.js:4:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
[2017-8-20 10:41:51] ====================
[2017-8-20 10:41:51] No plugins found. See the README for information on installing plugins.
[2017-8-20 10:41:51] Loaded config.json with 1 accessories and 0 platforms.
[2017-8-20 10:41:51] ---
[2017-8-20 10:41:51] Loading 0 platforms...
[2017-8-20 10:41:51] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Gaming-PC' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)`

My config-file looks like this, and yes it's in the root directory:
`
{   
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154",
        "manufacturer": "@nfarina",
        "model": "Homebridge",
        "serialNumber": "0.4.20"
    },

    "description": "Something",

    "accessories": [
   {
     "accessory": "Gaming-PC",
     "name": "DESKTOP-P86F3UU",
     "mac": "XX:XX:XX:XX:XX:XX",
     "ip": "192.168.15.30"
   }

    ],

    "platforms": [

    ]
}`

**Comment by AlexGustafsson** [comment]
Are you running the server on a Rasperry Pi or similar? The error seems to be that node-gyp (the build tool that compiles native modules) hasn't been run correctly on install. This is not your fault and can happen for various reasons. One of which is that node-gyp isn't installed on your system. Sometimes Rasperry Pis can be a tricky target for a Node environment.

What you could try is to install the beta which has no need for node-gyp usage since it has no native modules. This also removes the need for sudo / raw socket abilities. 

To install the beta, go over [here](https://github.com/AlexGustafsson/homebridge-wol/tree/beta) and follow the instructions.

**Comment by AlexGustafsson** [comment]
The beta has now been merged, so try the latest version of the package.

**Comment by nicknicknickos** [comment]
Having the same issue running on macOS. 

This happened after I updated to the latest version of nom (version 5.2.4). Here's the output from terminal:

`/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Computer' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3`

Here's module in the config.json (just that part of the json file):

{
			"accessory": "Computer",
			"name": "PC",
			"mac": "XX: XX: XX: XX: XX: XX",
			"ip": "192.168.1.72",
      "pingInterval": "0"
		}

Also, I'm running the latest version of the wol plugin.

**Comment by AlexGustafsson** [comment]
The error suggests that you haven't installed `homebridge-wol` correctly. Please run `npm ls -g homebridge-wol` on your mac.

**Comment by nicknicknickos** [comment]
Nick$ npm ls -g homebridge-wol
/usr/local/lib
└── homebridge-wol@3.1.0

**Comment by AlexGustafsson** [comment]
@nicknicknickos I have reason to believe your issue differ from this one. Please open a new issue and follow the template provided.

**Comment by nicknicknickos** [comment]
@AlexGustafsson - I figured it out. Turns out when I updated your plugin, I didn't change the "accessory" name to "NetworkDevice". That was breaking it in homebridge.

Thanks for taking a look!!

**Comment by AlexGustafsson** [comment]
@nicknicknickos I should've spotted that. Great thing you solved it. Do you think I could clarify the breaking change even more somehow?

**Comment by nicknicknickos** [comment]
@AlexGustafsson No worries :) 

I think this will only affect users who have an older version of the plugin, and then update with `npm install -g homebridge-wol`. New installers won't have this problem - and it was my fault for not reading the 'readme.md' file properly. Only when I looked at the stack trace a little closer did I figure it out.

Maybe you could add a section like:

'If you're updating from an older version of this plugin, be sure to follow these steps:
1- Run `npm ls -g homebridge-wol`
2- If version is older than _VERSION BEFORE NETWORKDEVICE ADDED_, please change your accessory name to 'NetworkDevice'.
3- Install the latest version of wol with `npm install -g homebridge-wol`
