### ISSUE TITLE
Following error when running

### ISSUE THREAD

**Issue by miguelmolez** [AlexGustafsson/homebridge-wol#4]
I get the following error when running this add on, it worked fine before I added it.

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:92:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by AlexGustafsson** [comment]
It doesn't seem to be a problem directly related to homebridge-wol. Perhaps you made a mistake when configuring Homebridge?

Furthermore, there have been a lot of improvements made lately with the help of @blubber. Be sure to update the homebridge-wol package and re-read the documentation to get updated on any news.

If the problem still persist, be sure to make an issue covering your problems.
