### ISSUE TITLE
Shutdown Command for Windows not working

### ISSUE THREAD

**Issue by nzstaneo** [AlexGustafsson/homebridge-wol#62]
Trying to Shutdown Remote Windows Machine from my Windows Homebridge Server with this plugin but keep getting an error:

The Shutdown Command looks as follows in the config file: 

"shutdownCommand": "shutdown -s -m \\media-pc",

And the error in homebridge is:

An error occured while trying to shut down "PC" (10.1.1.121): Error: Command failed: shutdown -s -m \media-pc
\media-pc: The network address is invalid.(1707)

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5) {
  killed: false,
  code: 1707,
  signal: null,
  cmd: 'shutdown -s -m \\media-pc'

Why does the log only read \media-pc and not \\media-pc from the config.json file?

I can confirm that when running the following command on the homebridge PC that it will initiate the shutdown correctly: shutdown -s -m \\media-pc 

Any help much appreciated,

**Comment by nzstaneo** [comment]
Friendly bump if anyone can help me, the plugin works brilliantly otherwise :)

**Comment by AlexGustafsson** [comment]
Could it be a problem with escaped strings? Try to escape the backslash by writing `\\media-pc` instead.

**Comment by nzstaneo** [comment]
Thanks, i can confirm in the config.json there are two backslashes \\

Here's the error again (note at the bottom it shows the CMD command with \\

[5/28/2019, 12:58:18 PM] [Computer] NetworkDevice "Computer" (10.1.1.153) went from status "Online" to "Shutting Down"
[5/28/2019, 12:58:18 PM] [Computer] An error occured while trying to shut down "Computer" (10.1.1.153): Error: Command failed: shutdown /s /m \media-pc -t 0
\media-pc: The network address is invalid.(1707)

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5) {
  killed: false,
  code: 1707,
  signal: null,
  cmd: 'shutdown /s /m \\media-pc -t 0'

**Comment by nzstaneo** [comment]
Hmmm....i just noticed it here aswell, when i use dual \\ it only shows one?

**Comment by AlexGustafsson** [comment]
Could you try four? It's entirely possible that they are interpreted once when I read the config file and once when they are run as a command, meaning it could be interpreted as escaping the letter 'm'.

**Comment by nzstaneo** [comment]
Thank you very much!!! It was the four I required and along the way I learnt a bit more about json files which will surely help me in the future
