### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by killervette** [AlexGustafsson/homebridge-wol#9]
/usr/lib/node_modules/homebridge-wol/node_modules/net-ping/node_modules/raw-socket/index.js:47
        this.wrap = new raw.SocketWrap (
I am getting this error after installing.  Here is my config:

     "accessory": "Computer",
     "name": "Upstairs",
     "mac": "40.15.8A.AE.75.C1",
     "ip": "192.168.1.10"

Error: Operation not permitted
    at Error (native)
    at new Socket (/usr/lib/node_modules/homebridge-wol/node_modules/net-ping/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/usr/lib/node_modules/homebridge-wol/node_modules/net-ping/node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (/usr/lib/node_modules/homebridge-wol/node_modules/net-ping/index.js:147:20)
    at new Session (/usr/lib/node_modules/homebridge-wol/node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (/usr/lib/node_modules/homebridge-wol/node_modules/net-ping/index.js:545:9)
    at new Pinger (/usr/lib/node_modules/homebridge-wol/index.js:114:24)
    at new Computer (/usr/lib/node_modules/homebridge-wol/index.js:28:16)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:244:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by AlexGustafsson** [comment]
This may be due to insufficient permissions. Can you rerun homebridge with sudo?

**Comment by blubber** [comment]
WOL requires root privileges, run homebrdige as root as @AlexGustafsson suggested. You can also try to use the raw socket capability, see `man 7 raw`

**Comment by killervette** [comment]
That did the trick!  thanks

**Comment by sowieso-stefan** [comment]
Hello, i`m new here. I hope my questions are not so stupid. I have installed hombridge and harmony plugin. It all works fine. I had installed homebridge-wol. After installation i have the same error as killervette. My knowledge in linux is no so good but i work on it. Can you tell me step by step what i must do? I know, its a problem with permissions but i dont understand what is the trick. I read the man-page but i don´t understand it. I hope you can help me.

**Comment by killervette** [comment]
Instead of typing homebridge to start it, type sudo homebridge. That will run it as root

**Comment by AlexGustafsson** [comment]
@sowieso-stefan: @killervette is correct. Try to run with root permission - that is `sudo homebridge`  to start.

**Comment by sowieso-stefan** [comment]
Thanks a lot. I try it and Hope it Works
