### ISSUE TITLE
Sudden error WOL plugin

### ISSUE THREAD

**Issue by tjitsejdevries** [AlexGustafsson/homebridge-wol#90]
Somhow I suddenly get this error in my Homebridge install. Until a few days this worked perfectly. 

Anyone know what might be wrong?

ERROR LOADING PLUGIN homebridge-wol:
[2020-2-2 18:35:45] /home/pi/.nvm/versions/node/v8.16.1/lib/node_modules/homebridge-wol/lib/pinger.js:32
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v8.16.1/lib/node_modules/homebridge-wol/lib/network-device.js:4:16)

**Comment by AlexGustafsson** [comment]
You'll have to update your Node version.

**Comment by AlexGustafsson** [comment]
Closing dure to inactivity. If you still have this issue after updating, please feel free to reopen the issue.
